### ISSUE TITLE
Fail to run create-react-app example tests

### ISSUE THREAD

**Issue by supromikali** [fwouts/react-screenshot-test#286]
Hi @fwouts 

thank you for the nice lib, it seems to have a convenient API with multiple screen resolutions support and encapsulates the whole puppeteer/Docker setup problem making the testing easier, so I decided to give it a try. However I hit some issue while running the test for the first time: `Error: socket hang up` (I have posted the full error output below). 

My steps: clone the repo, npm install, pull docker image, npm run screenshot-test-local
My environment is: Ubuntu 16, Node 12, Docker 19

Could you have a look please?
```
/react-screenshot-test-with-create-react-app-master
> jest -c jest.screenshot.config.js

 FAIL  src/App.screenshot.jsx (10.426s)
  App
    Desktop
      ✕ app (5004ms)
    iPhone X
      ✕ app (5002ms)

  ● App › Desktop › app

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:141:25)

  ● App › iPhone X › app

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:141:25)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        10.445s
Ran all test suites.
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketOnEnd (_http_client.js:459:9)
    at Socket.emit (events.js:326:22)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-screenshot-test-example@0.1.0 screenshot-test-local: `jest -c jest.screenshot.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-screenshot-test-example@0.1.0 screenshot-test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2020-11-06T07_50_51_545Z-debug.log
```

**Comment by fwouts** [comment]
Hi Alexander,

Thanks for the bug report. It looks like either:
- Docker is not running
- or the Docker socket is not available on /var/run/docker.sock

I suspect the latter. Here is the code in question:
https://github.com/fwouts/react-screenshot-test/blob/b525cf4486b70678b998a4e460cf6dea212138cf/src/lib/screenshot-server/DockerizedScreenshotServer.ts#L24

Would you be able to confirm the path of your Docker socket?

As an alternative, you can also run without Docker by setting the
SCREENSHOT_MODE env variable to "local".

Let me know how you go!

**Comment by supromikali** [comment]
Hi François,

thanks for the quick reply! you were right and the issue was that I didn't start the docker container (only loaded an image). Probably it would be nice to add to the README somewhere that the docker container should be started manually.

so, I run docker container like follows:
```
$ docker run fwouts/chrome-screenshot:1.1.0
Ready.
```

After that I run the test and get the new error: `Unable to reach screenshot server. `

Here is the configuration of the jest.screenshot.config.js that I use https://github.com/supromikali/react-screenshot-test-with-create-react-app/blob/master/jest.screenshot.config.js

```
> jest -c jest.screenshot.config.js

 FAIL  src/App.screenshot.jsx
  App
    Desktop
      ✕ app (5ms)
    iPhone X
      ✕ app (1ms)

  ● App › Desktop › app

    TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function

      at Promise (node_modules/react-screenshot-test/dist/lib/network/fetch.js:18:40)
      at Object.fetch (node_modules/react-screenshot-test/dist/lib/network/fetch.js:17:12)
      at ReactScreenshotTest.render (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:175:44)
      at componentServer.serve (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:152:45)
      at ReactComponentServer.serve (node_modules/react-screenshot-test/dist/lib/react/ReactComponentServer.js:129:30)
      at Object.it (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:144:70)

  ● App › iPhone X › app

    TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function

      at Promise (node_modules/react-screenshot-test/dist/lib/network/fetch.js:18:40)
      at Object.fetch (node_modules/react-screenshot-test/dist/lib/network/fetch.js:17:12)
      at ReactScreenshotTest.render (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:175:44)
      at componentServer.serve (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:152:45)
      at ReactComponentServer.serve (node_modules/react-screenshot-test/dist/lib/react/ReactComponentServer.js:129:30)
      at Object.it (node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:144:70)

  console.error node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:188
    Unable to reach screenshot server. Please make sure that your Jest configuration contains the following:
    
    {
      "globalSetup": "react-screenshot-test/global-setup",
      "globalTeardown": "react-screenshot-test/global-teardown"
    }
    

  console.error node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:188
    Unable to reach screenshot server. Please make sure that your Jest configuration contains the following:
    
    {
      "globalSetup": "react-screenshot-test/global-setup",
      "globalTeardown": "react-screenshot-test/global-teardown"
    }
    

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        0.854s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-screenshot-test-example@0.1.0 screenshot-test-local: `jest -c jest.screenshot.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-screenshot-test-example@0.1.0 screenshot-test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2020-11-08T13_51_16_621Z-debug.log
```

**Comment by supromikali** [comment]
> As an alternative, you can also run without Docker by setting the
SCREENSHOT_MODE env variable to "local".

This worked fine for me after I installed the puppeteer package, thanks! But the output on my local Ubuntu has diff (so running the docker is still a good idea)

![Desktop - app-diff](https://user-images.githubusercontent.com/22643362/98467342-d635a780-21e5-11eb-8bc5-781a097867fd.png)

**Comment by tdloi** [comment]
> After that I run the test and get the new error: Unable to reach screenshot server.

I think it's problem with building package, have you tried using `yarn` (try fresh install without cache)? I also have some errors about types conflict (incorrect type) when installing `react-screenshot-test` with npm
