### ISSUE TITLE
react-screenshot-test/css-transform rejects an simply project by importing css

### ISSUE THREAD

**Issue by aiya000** [fwouts/react-screenshot-test#324]
Hi, thank you for present this good library.

I have a problem, that can be seen at [here](https://github.com/aiya000/osatou-sugar-life-publisher/commit/cea63e1ddb4e3d5aa826287422e2c1277c08d523)

- https://github.com/aiya000/osatou-sugar-life-publisher/commit/cea63e1ddb4e3d5aa826287422e2c1277c08d523

 In this project, running `$ npm run screenshot`, it says:
 
 ```
 > screenshot
> SCREENSHOT_MODE=local jest -c jest.screenshot.config.ts -u

 FAIL  screenshots/about.tsx
  ● Test suite failed to run

    TypeError: Cannot destructure property 'instrument' of 'undefined' as it is undefined.

      at Object.getCacheKey (node_modules/react-screenshot-test/css-transform/index.js:11:53)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:282:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:353:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:596:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:766:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:823:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.958 s
Ran all test suites.
```

Why it rejects style.css?

Thank you.

**Comment by fwouts** [comment]
Hi @aiya000, I'm not sure but you may want to try https://github.com/fwouts/viteshot, which is the successor of react-screenshot-test :)

**Comment by aiya000** [comment]
Thank you! ✨
I'll try it if necessary :D
